# Generated by Django 3.1.2 on 2020-10-01 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('category', models.CharField(
                    choices=[('mc', 'Multiple Choice'), ('sa', 'Short answer')],
                    max_length=2)),
                ('quiz',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='questions',
                                   to='profiles.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('correct', models.BooleanField()),
                ('question',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='options',
                                   to='profiles.question')),
            ],
        ),
    ]
